baseURL = "http://118.24.78.115"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Never Give Up"                    # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                         # shows the number of articles  # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                 # your google analytics id
disqusShortname = ""                 # your discuss shortname

[author]                             # essential                     # 必需
  name = "Zeuk"

[blackfriday]
  smartypants = false

[[menu.main]]                        # config your menu  # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "分类"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  url = "/about/about"

[params]
  subTitle = ""                                       # site's subTitle  # 网站二级标题
  keywords = ["Hugo", "theme", "blog", "moweiwei", "mww"]                                  # site's keywords  # 网站关键字
  description = "moweiwei blog."                        # site's description  # 网站描述

# mathjax
  enableMathJax = true                                                 # enable mathjax  # 是否使用mathjax（数学公式）

  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = " "
  visitor = true

[social]
  github = "https://github.com/MFullStack?tab=repositories"

[taxonomies]
  category = "categories"
  tag = "tags"

[params.counter.busuanzi]
  enable = true

[highlighting]
  pygmentsUseClassic       = true
  pygmentsCodeFences       = true
  pygmentsStyle            = "monokai"